// interviewInput
const MAXIMUM_COVERLETTER_NUMBER = 3;

const MAX_COMPANY_NAME_LENGTH = 15;
const MAX_POSITION_NAME_LENGTH = 30;
const MAX_RECRUITMENT_LENGTH = 1000;
const MAX_COVERLETTER_QUESTION_LENGTH = 100;
const MAX_COVERLETTER_ANSWER_LENGTH = 1500;

// interviewLightInput
const MAX_KEYWORD_LENGTH = 30;

export {
  MAXIMUM_COVERLETTER_NUMBER,
  MAX_COMPANY_NAME_LENGTH,
  MAX_POSITION_NAME_LENGTH,
  MAX_RECRUITMENT_LENGTH,
  MAX_COVERLETTER_QUESTION_LENGTH,
  MAX_COVERLETTER_ANSWER_LENGTH,
  MAX_KEYWORD_LENGTH,
};